server:
 port: 8051 # Default Port
---
# My Sql Connection Properties
spring:
  datasource:
    url: ${db_mysql_url}
    username: ${db_mysql_username}
    password: ${db_mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
---
